/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Greet: typeof import('./src/components/Greet.vue')['default']
    Hotkey: typeof import('./src/components/Settings/Hotkey.vue')['default']
    Interval: typeof import('./src/components/Settings/Interval.vue')['default']
    LabelContainer: typeof import('./src/components/Util/LabelContainer.vue')['default']
    Loading: typeof import('./src/components/Util/Loading.vue')['default']
    LockableWindows: typeof import('./src/components/Settings/LockableWindows.vue')['default']
    NumberInput: typeof import('./src/components/Inputs/NumberInput.vue')['default']
    SectionContainer: typeof import('./src/components/Util/SectionContainer.vue')['default']
    Status: typeof import('./src/components/Settings/Status.vue')['default']
    SwitchInput: typeof import('./src/components/Inputs/SwitchInput.vue')['default']
  }
}
